name: Run Benchmarks and Commit Results

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Optional cache: apt packages (C++ toolchain)
      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}

      - name: Install C++ toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Cache Python packages
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      - name: Run full pipeline
        run: |
          chmod +x script/run_benchmarks.sh
          make run

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/
          if ! git diff --staged --quiet; then
            git commit -m "Update benchmark results and plots"
            git push
          else
            echo "No changes to commit."
